url: https://www.louishoughton.com
baseurl: https://www.louishoughton.com
title: Louis Houghton Software Development
description: >
  Independent Software Consultancy
twitter_username: louisblack
github_username: louisblack
