url: http://www.louishoughton.com
baseurl: http://www.louishoughton.com
title: Stuff and Things
description: >
  Murmurings from the mind of Louis Houghton
twitter_username: louisblack
github_username: louisblack
